/*

TABLE À IMPORTER DANS UNE B.D. EXISTANTE
THÈME: Jeux Olympiques d'hiver 2022

Il y a 109 épreuves et autant de médailles (Or, Argent et Bronze)
Donc 327 médailles au total.

Note: Un sport peut avoir plusieurs épreuves et certaines
épreuves peuvent avoir le même nom dans plusieurs sports.

Requête pour calculer le nombre d'épreuves:
SELECT COUNT(*) AS Épreuves_Total
FROM (
    SELECT DISTINCT sport, epreuve 
    FROM Medailles_JO_2022
) AS sous_requete;

*/

DROP TABLE IF EXISTS Medailles_JO_2022;
CREATE TABLE Medailles_JO_2022 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pays VARCHAR(50),
    sport VARCHAR(50),
    epreuve VARCHAR(100),
    athlete VARCHAR(255),
    medaille VARCHAR(10),
    date_evenement DATE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO Medailles_JO_2022 (pays, sport, epreuve, athlete, medaille, date_evenement) VALUES
-- BIATHLON
('Norvège', 'Biathlon', '10km Sprint Hommes', 'Johannes Thingnes Bø', 'Or', '2022-02-12'),
('France', 'Biathlon', '10km Sprint Hommes', 'Quentin Fillon Maillet', 'Argent', '2022-02-12'),
('Norvège', 'Biathlon', '10km Sprint Hommes', 'Tarjei Bø', 'Bronze', '2022-02-12'),
('France', 'Biathlon', '20km Individuel Hommes', 'Quentin Fillon Maillet', 'Or', '2022-02-08'),
('Biélorussie', 'Biathlon', '20km Individuel Hommes', 'Anton Smolski', 'Argent', '2022-02-08'),
('Norvège', 'Biathlon', '20km Individuel Hommes', 'Johannes Thingnes Bø', 'Bronze', '2022-02-08'),
('France', 'Biathlon', '12.5km Poursuite Hommes', 'Quentin Fillon Maillet', 'Or', '2022-02-13'),
('Norvège', 'Biathlon', '12.5km Poursuite Hommes', 'Tarjei Bø', 'Argent', '2022-02-13'),
('ROC', 'Biathlon', '12.5km Poursuite Hommes', 'Eduard Latypov', 'Bronze', '2022-02-13'),
('Norvège', 'Biathlon', '15km Mass Start Hommes', 'Johannes Thingnes Bø', 'Or', '2022-02-18'),
('Suède', 'Biathlon', '15km Mass Start Hommes', 'Martin Ponsiluoma', 'Argent', '2022-02-18'),
('Norvège', 'Biathlon', '15km Mass Start Hommes', 'Vetle Sjåstad Christiansen', 'Bronze', '2022-02-18'),
('Norvège', 'Biathlon', 'Relais 4x7.5km Hommes', 'Équipe Norvège', 'Or', '2022-02-15'),
('France', 'Biathlon', 'Relais 4x7.5km Hommes', 'Équipe France', 'Argent', '2022-02-15'),
('ROC', 'Biathlon', 'Relais 4x7.5km Hommes', 'Équipe ROC', 'Bronze', '2022-02-15'),
('Norvège', 'Biathlon', '7.5km Sprint Femmes', 'Marte Olsbu Røiseland', 'Or', '2022-02-11'),
('Suède', 'Biathlon', '7.5km Sprint Femmes', 'Elvira Öberg', 'Argent', '2022-02-11'),
('Italie', 'Biathlon', '7.5km Sprint Femmes', 'Dorothea Wierer', 'Bronze', '2022-02-11'),
('Allemagne', 'Biathlon', '15km Individuel Femmes', 'Denise Herrmann', 'Or', '2022-02-07'),
('France', 'Biathlon', '15km Individuel Femmes', 'Anaïs Chevalier-Bouchet', 'Argent', '2022-02-07'),
('Norvège', 'Biathlon', '15km Individuel Femmes', 'Marte Olsbu Røiseland', 'Bronze', '2022-02-07'),
('Norvège', 'Biathlon', '10km Poursuite Femmes', 'Marte Olsbu Røiseland', 'Or', '2022-02-13'),
('Suède', 'Biathlon', '10km Poursuite Femmes', 'Elvira Öberg', 'Argent', '2022-02-13'),
('Norvège', 'Biathlon', '10km Poursuite Femmes', 'Tiril Eckhoff', 'Bronze', '2022-02-13'),
('France', 'Biathlon', '12.5km Mass Start Femmes', 'Justine Braisaz-Bouchet', 'Or', '2022-02-18'),
('Norvège', 'Biathlon', '12.5km Mass Start Femmes', 'Tiril Eckhoff', 'Argent', '2022-02-18'),
('Norvège', 'Biathlon', '12.5km Mass Start Femmes', 'Marte Olsbu Røiseland', 'Bronze', '2022-02-18'),
('Suède', 'Biathlon', 'Relais 4x6km Femmes', 'Équipe Suède', 'Or', '2022-02-16'),
('ROC', 'Biathlon', 'Relais 4x6km Femmes', 'Équipe ROC', 'Argent', '2022-02-16'),
('Allemagne', 'Biathlon', 'Relais 4x6km Femmes', 'Équipe Allemagne', 'Bronze', '2022-02-16'),
('Norvège', 'Biathlon', 'Relais Mixte 4x6km', 'Équipe Norvège', 'Or', '2022-02-05'),
('France', 'Biathlon', 'Relais Mixte 4x6km', 'Équipe France', 'Argent', '2022-02-05'),
('ROC', 'Biathlon', 'Relais Mixte 4x6km', 'Équipe ROC', 'Bronze', '2022-02-05'),

-- SKI ALPIN
('Suisse', 'Ski Alpin', 'Descente Hommes', 'Beat Feuz', 'Or', '2022-02-07'),
('France', 'Ski Alpin', 'Descente Hommes', 'Johan Clarey', 'Argent', '2022-02-07'),
('Autriche', 'Ski Alpin', 'Descente Hommes', 'Matthias Mayer', 'Bronze', '2022-02-07'),
('Autriche', 'Ski Alpin', 'Super-G Hommes', 'Matthias Mayer', 'Or', '2022-02-08'),
('États-Unis', 'Ski Alpin', 'Super-G Hommes', 'Ryan Cochran-Siegle', 'Argent', '2022-02-08'),
('Norvège', 'Ski Alpin', 'Super-G Hommes', 'Aleksander Aamodt Kilde', 'Bronze', '2022-02-08'),
('Suisse', 'Ski Alpin', 'Slalom Géant Hommes', 'Marco Odermatt', 'Or', '2022-02-13'),
('Slovénie', 'Ski Alpin', 'Slalom Géant Hommes', 'Žan Kranjec', 'Argent', '2022-02-13'),
('France', 'Ski Alpin', 'Slalom Géant Hommes', 'Mathieu Faivre', 'Bronze', '2022-02-13'),
('France', 'Ski Alpin', 'Slalom Hommes', 'Clément Noël', 'Or', '2022-02-16'),
('Autriche', 'Ski Alpin', 'Slalom Hommes', 'Johannes Strolz', 'Argent', '2022-02-16'),
('Norvège', 'Ski Alpin', 'Slalom Hommes', 'Sebastian Foss-Solevåg', 'Bronze', '2022-02-16'),
('Autriche', 'Ski Alpin', 'Combiné Alpin Hommes', 'Johannes Strolz', 'Or', '2022-02-10'),
('Norvège', 'Ski Alpin', 'Combiné Alpin Hommes', 'Aleksander Aamodt Kilde', 'Argent', '2022-02-10'),
('Canada', 'Ski Alpin', 'Combiné Alpin Hommes', 'James Crawford', 'Bronze', '2022-02-10'),
('Suisse', 'Ski Alpin', 'Descente Femmes', 'Corinne Suter', 'Or', '2022-02-15'),
('Italie', 'Ski Alpin', 'Descente Femmes', 'Sofia Goggia', 'Argent', '2022-02-15'),
('Italie', 'Ski Alpin', 'Descente Femmes', 'Nadia Delago', 'Bronze', '2022-02-15'),
('Suisse', 'Ski Alpin', 'Super-G Femmes', 'Lara Gut-Behrami', 'Or', '2022-02-11'),
('Autriche', 'Ski Alpin', 'Super-G Femmes', 'Mirjam Puchner', 'Argent', '2022-02-11'),
('Suisse', 'Ski Alpin', 'Super-G Femmes', 'Michelle Gisin', 'Bronze', '2022-02-11'),
('Suède', 'Ski Alpin', 'Slalom Géant Femmes', 'Sara Hector', 'Or', '2022-02-07'),
('Italie', 'Ski Alpin', 'Slalom Géant Femmes', 'Federica Brignone', 'Argent', '2022-02-07'),
('Suisse', 'Ski Alpin', 'Slalom Géant Femmes', 'Lara Gut-Behrami', 'Bronze', '2022-02-07'),
('Slovaquie', 'Ski Alpin', 'Slalom Femmes', 'Petra Vlhová', 'Or', '2022-02-09'),
('Autriche', 'Ski Alpin', 'Slalom Femmes', 'Katharina Liensberger', 'Argent', '2022-02-09'),
('Suisse', 'Ski Alpin', 'Slalom Femmes', 'Wendy Holdener', 'Bronze', '2022-02-09'),
('Suisse', 'Ski Alpin', 'Combiné Alpin Femmes', 'Michelle Gisin', 'Or', '2022-02-17'),
('Suisse', 'Ski Alpin', 'Combiné Alpin Femmes', 'Wendy Holdener', 'Argent', '2022-02-17'),
('Italie', 'Ski Alpin', 'Combiné Alpin Femmes', 'Federica Brignone', 'Bronze', '2022-02-17'),
('Autriche', 'Ski Alpin', 'Épreuve par Équipe Mixte', 'Équipe Autriche', 'Or', '2022-02-20'),
('Allemagne', 'Ski Alpin', 'Épreuve par Équipe Mixte', 'Équipe Allemagne', 'Argent', '2022-02-20'),
('Norvège', 'Ski Alpin', 'Épreuve par Équipe Mixte', 'Équipe Norvège', 'Bronze', '2022-02-20'),

-- PATINAGE ARTISTIQUE
('États-Unis', 'Patinage Artistique', 'Individuel Hommes', 'Nathan Chen', 'Or', '2022-02-10'),
('Japon', 'Patinage Artistique', 'Individuel Hommes', 'Yuma Kagiyama', 'Argent', '2022-02-10'),
('Japon', 'Patinage Artistique', 'Individuel Hommes', 'Shoma Uno', 'Bronze', '2022-02-10'),
('ROC', 'Patinage Artistique', 'Individuel Femmes', 'Anna Shcherbakova', 'Or', '2022-02-17'),
('ROC', 'Patinage Artistique', 'Individuel Femmes', 'Alexandra Trusova', 'Argent', '2022-02-17'),
('Japon', 'Patinage Artistique', 'Individuel Femmes', 'Kaori Sakamoto', 'Bronze', '2022-02-17'),
('Chine', 'Patinage Artistique', 'Couples', 'Sui Wenjing / Han Cong', 'Or', '2022-02-19'),
('ROC', 'Patinage Artistique', 'Couples', 'Tarasova / Morozov', 'Argent', '2022-02-19'),
('ROC', 'Patinage Artistique', 'Couples', 'Mishina / Galliamov', 'Bronze', '2022-02-19'),
('France', 'Patinage Artistique', 'Danse sur Glace', 'Papadakis / Cizeron', 'Or', '2022-02-14'),
('ROC', 'Patinage Artistique', 'Danse sur Glace', 'Sinitsina / Katsalapov', 'Argent', '2022-02-14'),
('États-Unis', 'Patinage Artistique', 'Danse sur Glace', 'Hubbell / Donohue', 'Bronze', '2022-02-14'),
('ROC', 'Patinage Artistique', 'Épreuve par Équipe', 'Équipe ROC', 'Or', '2022-02-07'),
('États-Unis', 'Patinage Artistique', 'Épreuve par Équipe', 'Équipe USA', 'Argent', '2022-02-07'),
('Japon', 'Patinage Artistique', 'Épreuve par Équipe', 'Équipe Japon', 'Bronze', '2022-02-07'),

-- HOCKEY SUR GLACE
('Finlande', 'Hockey sur Glace', 'Tournoi Hommes', 'Équipe Finlande', 'Or', '2022-02-20'),
('ROC', 'Hockey sur Glace', 'Tournoi Hommes', 'Équipe ROC', 'Argent', '2022-02-20'),
('Slovaquie', 'Hockey sur Glace', 'Tournoi Hommes', 'Équipe Slovaquie', 'Bronze', '2022-02-19'),
('Canada', 'Hockey sur Glace', 'Tournoi Femmes', 'Équipe Canada', 'Or', '2022-02-17'),
('États-Unis', 'Hockey sur Glace', 'Tournoi Femmes', 'Équipe USA', 'Argent', '2022-02-17'),
('Finlande', 'Hockey sur Glace', 'Tournoi Femmes', 'Équipe Finlande', 'Bronze', '2022-02-16'),

-- CURLING
('Suède', 'Curling', 'Tournoi Hommes', 'Équipe Niklas Edin', 'Or', '2022-02-19'),
('Grande-Bretagne', 'Curling', 'Tournoi Hommes', 'Équipe Bruce Mouat', 'Argent', '2022-02-19'),
('Canada', 'Curling', 'Tournoi Hommes', 'Équipe Brad Gushue', 'Bronze', '2022-02-18'),
('Grande-Bretagne', 'Curling', 'Tournoi Femmes', 'Équipe Eve Muirhead', 'Or', '2022-02-20'),
('Japon', 'Curling', 'Tournoi Femmes', 'Équipe Satsuki Fujisawa', 'Argent', '2022-02-20'),
('Suède', 'Curling', 'Tournoi Femmes', 'Équipe Anna Hasselborg', 'Bronze', '2022-02-19'),
('Italie', 'Curling', 'Double Mixte', 'Constantini / Mosaner', 'Or', '2022-02-08'),
('Norvège', 'Curling', 'Double Mixte', 'Skaslien / Nedregotten', 'Argent', '2022-02-08'),
('Suède', 'Curling', 'Double Mixte', 'De Val / Eriksson', 'Bronze', '2022-02-08'),

-- SKI ACROBATIQUE
('Chine', 'Ski Acrobatique', 'Big Air Femmes', 'Eileen Gu', 'Or', '2022-02-08'),
('France', 'Ski Acrobatique', 'Big Air Femmes', 'Tess Ledeux', 'Argent', '2022-02-08'),
('Suisse', 'Ski Acrobatique', 'Big Air Femmes', 'Mathilde Gremaud', 'Bronze', '2022-02-08'),
('Norvège', 'Ski Acrobatique', 'Big Air Hommes', 'Birk Ruud', 'Or', '2022-02-09'),
('États-Unis', 'Ski Acrobatique', 'Big Air Hommes', 'Colby Stevenson', 'Argent', '2022-02-09'),
('Suède', 'Ski Acrobatique', 'Big Air Hommes', 'Henrik Harlaut', 'Bronze', '2022-02-09'),
('Chine', 'Ski Acrobatique', 'Saut Femmes', 'Xu Mengtao', 'Or', '2022-02-14'),
('Biélorussie', 'Ski Acrobatique', 'Saut Femmes', 'Hanna Huskova', 'Argent', '2022-02-14'),
('États-Unis', 'Ski Acrobatique', 'Saut Femmes', 'Megan Nick', 'Bronze', '2022-02-14'),
('Chine', 'Ski Acrobatique', 'Saut Hommes', 'Qi Guangpu', 'Or', '2022-02-16'),
('Ukraine', 'Ski Acrobatique', 'Saut Hommes', 'Oleksandr Abramenko', 'Argent', '2022-02-16'),
('ROC', 'Ski Acrobatique', 'Saut Hommes', 'Ilya Burov', 'Bronze', '2022-02-16'),
('États-Unis', 'Ski Acrobatique', 'Saut Équipe Mixte', 'Équipe USA', 'Or', '2022-02-10'),
('Chine', 'Ski Acrobatique', 'Saut Équipe Mixte', 'Équipe Chine', 'Argent', '2022-02-10'),
('Canada', 'Ski Acrobatique', 'Saut Équipe Mixte', 'Équipe Canada', 'Bronze', '2022-02-10'),
('Suisse', 'Ski Acrobatique', 'Slopestyle Femmes', 'Mathilde Gremaud', 'Or', '2022-02-15'),
('Chine', 'Ski Acrobatique', 'Slopestyle Femmes', 'Eileen Gu', 'Argent', '2022-02-15'),
('Estonie', 'Ski Acrobatique', 'Slopestyle Femmes', 'Kelly Sildaru', 'Bronze', '2022-02-15'),
('États-Unis', 'Ski Acrobatique', 'Slopestyle Hommes', 'Alexander Hall', 'Or', '2022-02-16'),
('États-Unis', 'Ski Acrobatique', 'Slopestyle Hommes', 'Nick Goepper', 'Argent', '2022-02-16'),
('Suède', 'Ski Acrobatique', 'Slopestyle Hommes', 'Jesper Tjäder', 'Bronze', '2022-02-16'),
('Chine', 'Ski Acrobatique', 'Halfpipe Femmes', 'Eileen Gu', 'Or', '2022-02-18'),
('Canada', 'Ski Acrobatique', 'Halfpipe Femmes', 'Cassie Sharpe', 'Argent', '2022-02-18'),
('Canada', 'Ski Acrobatique', 'Halfpipe Femmes', 'Rachael Karker', 'Bronze', '2022-02-18'),
('Nouvelle-Zélande', 'Ski Acrobatique', 'Halfpipe Hommes', 'Nico Porteous', 'Or', '2022-02-19'),
('États-Unis', 'Ski Acrobatique', 'Halfpipe Hommes', 'David Wise', 'Argent', '2022-02-19'),
('États-Unis', 'Ski Acrobatique', 'Halfpipe Hommes', 'Alex Ferreira', 'Bronze', '2022-02-19'),
('Suède', 'Ski Acrobatique', 'Ski Cross Femmes', 'Sandra Näslund', 'Or', '2022-02-17'),
('Canada', 'Ski Acrobatique', 'Ski Cross Femmes', 'Marielle Thompson', 'Argent', '2022-02-17'),
('Allemagne', 'Ski Acrobatique', 'Ski Cross Femmes', 'Daniela Maier', 'Bronze', '2022-02-17'),
('Suisse', 'Ski Acrobatique', 'Ski Cross Hommes', 'Ryan Regez', 'Or', '2022-02-18'),
('Suisse', 'Ski Acrobatique', 'Ski Cross Hommes', 'Alex Fiva', 'Argent', '2022-02-18'),
('ROC', 'Ski Acrobatique', 'Ski Cross Hommes', 'Sergey Ridzik', 'Bronze', '2022-02-18'),
('Australie', 'Ski Acrobatique', 'Bosses Femmes', 'Jakara Anthony', 'Or', '2022-02-06'),
('États-Unis', 'Ski Acrobatique', 'Bosses Femmes', 'Jaelin Kauf', 'Argent', '2022-02-06'),
('ROC', 'Ski Acrobatique', 'Bosses Femmes', 'Anastasiia Smirnova', 'Bronze', '2022-02-06'),
('Suède', 'Ski Acrobatique', 'Bosses Hommes', 'Walter Wallberg', 'Or', '2022-02-05'),
('Canada', 'Ski Acrobatique', 'Bosses Hommes', 'Mikaël Kingsbury', 'Argent', '2022-02-05'),
('Japon', 'Ski Acrobatique', 'Bosses Hommes', 'Ikuma Horishima', 'Bronze', '2022-02-05'),

-- SNOWBOARD
('Nouvelle-Zélande', 'Snowboard', 'Slopestyle Femmes', 'Zoi Sadowski-Synnott', 'Or', '2022-02-06'),
('États-Unis', 'Snowboard', 'Slopestyle Femmes', 'Julia Marino', 'Argent', '2022-02-06'),
('Australie', 'Snowboard', 'Slopestyle Femmes', 'Tess Coady', 'Bronze', '2022-02-06'),
('Canada', 'Snowboard', 'Slopestyle Hommes', 'Max Parrot', 'Or', '2022-02-07'),
('Chine', 'Snowboard', 'Slopestyle Hommes', 'Su Yiming', 'Argent', '2022-02-07'),
('Canada', 'Snowboard', 'Slopestyle Hommes', 'Mark McMorris', 'Bronze', '2022-02-07'),
('Autriche', 'Snowboard', 'Big Air Femmes', 'Anna Gasser', 'Or', '2022-02-15'),
('Nouvelle-Zélande', 'Snowboard', 'Big Air Femmes', 'Zoi Sadowski-Synnott', 'Argent', '2022-02-15'),
('Japon', 'Snowboard', 'Big Air Femmes', 'Kokomo Murase', 'Bronze', '2022-02-15'),
('Chine', 'Snowboard', 'Big Air Hommes', 'Su Yiming', 'Or', '2022-02-15'),
('Norvège', 'Snowboard', 'Big Air Hommes', 'Mons Røisland', 'Argent', '2022-02-15'),
('Canada', 'Snowboard', 'Big Air Hommes', 'Max Parrot', 'Bronze', '2022-02-15'),
('États-Unis', 'Snowboard', 'Halfpipe Femmes', 'Chloe Kim', 'Or', '2022-02-10'),
('Espagne', 'Snowboard', 'Halfpipe Femmes', 'Queralt Castellet', 'Argent', '2022-02-10'),
('Japon', 'Snowboard', 'Halfpipe Femmes', 'Sena Tomita', 'Bronze', '2022-02-10'),
('Japon', 'Snowboard', 'Halfpipe Hommes', 'Ayumu Hirano', 'Or', '2022-02-11'),
('Australie', 'Snowboard', 'Halfpipe Hommes', 'Scotty James', 'Argent', '2022-02-11'),
('Suisse', 'Snowboard', 'Halfpipe Hommes', 'Jan Scherrer', 'Bronze', '2022-02-11'),
('République Tchèque', 'Snowboard', 'Slalom Géant Parallèle Femmes', 'Ester Ledecká', 'Or', '2022-02-08'),
('Autriche', 'Snowboard', 'Slalom Géant Parallèle Femmes', 'Daniela Ulbing', 'Argent', '2022-02-08'),
('Slovénie', 'Snowboard', 'Slalom Géant Parallèle Femmes', 'Glorija Kotnik', 'Bronze', '2022-02-08'),
('Autriche', 'Snowboard', 'Slalom Géant Parallèle Hommes', 'Benjamin Karl', 'Or', '2022-02-08'),
('Slovénie', 'Snowboard', 'Slalom Géant Parallèle Hommes', 'Tim Mastnak', 'Argent', '2022-02-08'),
('ROC', 'Snowboard', 'Slalom Géant Parallèle Hommes', 'Vic Wild', 'Bronze', '2022-02-08'),
('États-Unis', 'Snowboard', 'Snowboard Cross Femmes', 'Lindsey Jacobellis', 'Or', '2022-02-09'),
('France', 'Snowboard', 'Snowboard Cross Femmes', 'Chloé Trespeuch', 'Argent', '2022-02-09'),
('Canada', 'Snowboard', 'Snowboard Cross Femmes', 'Meryeta O\'Dine', 'Bronze', '2022-02-09'),
('Autriche', 'Snowboard', 'Snowboard Cross Hommes', 'Alessandro Hämmerle', 'Or', '2022-02-10'),
('Canada', 'Snowboard', 'Snowboard Cross Hommes', 'Eliot Grondin', 'Argent', '2022-02-10'),
('Italie', 'Snowboard', 'Snowboard Cross Hommes', 'Omar Visintin', 'Bronze', '2022-02-10'),
('États-Unis', 'Snowboard', 'Snowboard Cross Équipe Mixte', 'Jacobellis / Baumgartner', 'Or', '2022-02-12'),
('Italie', 'Snowboard', 'Snowboard Cross Équipe Mixte', 'Moioli / Visintin', 'Argent', '2022-02-12'),
('Canada', 'Snowboard', 'Snowboard Cross Équipe Mixte', 'O\'Dine / Grondin', 'Bronze', '2022-02-12'),

-- LUGE
('Allemagne', 'Luge', 'Monoplace Hommes', 'Johannes Ludwig', 'Or', '2022-02-06'),
('Autriche', 'Luge', 'Monoplace Hommes', 'Wolfgang Kindl', 'Argent', '2022-02-06'),
('Italie', 'Luge', 'Monoplace Hommes', 'Dominik Fischnaller', 'Bronze', '2022-02-06'),
('Allemagne', 'Luge', 'Monoplace Femmes', 'Natalie Geisenberger', 'Or', '2022-02-08'),
('Allemagne', 'Luge', 'Monoplace Femmes', 'Anna Berreiter', 'Argent', '2022-02-08'),
('ROC', 'Luge', 'Monoplace Femmes', 'Tatiana Ivanova', 'Bronze', '2022-02-08'),
('Allemagne', 'Luge', 'Biplace', 'Wendl / Arlt', 'Or', '2022-02-09'),
('Allemagne', 'Luge', 'Biplace', 'Eggert / Benecken', 'Argent', '2022-02-09'),
('Autriche', 'Luge', 'Biplace', 'Steu / Koller', 'Bronze', '2022-02-09'),
('Allemagne', 'Luge', 'Relais par Équipe', 'Équipe Allemagne', 'Or', '2022-02-10'),
('Autriche', 'Luge', 'Relais par Équipe', 'Équipe Autriche', 'Argent', '2022-02-10'),
('Lettonie', 'Luge', 'Relais par Équipe', 'Équipe Lettonie', 'Bronze', '2022-02-10'),

-- BOBSLEIGH & SKELETON
('Allemagne', 'Skeleton', 'Hommes', 'Christopher Grotheer', 'Or', '2022-02-11'),
('Allemagne', 'Skeleton', 'Hommes', 'Axel Jungk', 'Argent', '2022-02-11'),
('Chine', 'Skeleton', 'Hommes', 'Yan Wengang', 'Bronze', '2022-02-11'),
('Allemagne', 'Skeleton', 'Femmes', 'Hannah Neise', 'Or', '2022-02-12'),
('Australie', 'Skeleton', 'Femmes', 'Jaclyn Narracott', 'Argent', '2022-02-12'),
('Pays-Bas', 'Skeleton', 'Femmes', 'Kimberley Bos', 'Bronze', '2022-02-12'),
('États-Unis', 'Bobsleigh', 'Monobob Femmes', 'Kaillie Humphries', 'Or', '2022-02-14'),
('États-Unis', 'Bobsleigh', 'Monobob Femmes', 'Elana Meyers Taylor', 'Argent', '2022-02-14'),
('Canada', 'Bobsleigh', 'Monobob Femmes', 'Christine de Bruin', 'Bronze', '2022-02-14'),
('Allemagne', 'Bobsleigh', 'Bob à deux Hommes', 'Francesco Friedrich', 'Or', '2022-02-15'),
('Allemagne', 'Bobsleigh', 'Bob à deux Hommes', 'Johannes Lochner', 'Argent', '2022-02-15'),
('Allemagne', 'Bobsleigh', 'Bob à deux Hommes', 'Christoph Hafer', 'Bronze', '2022-02-15'),
('Allemagne', 'Bobsleigh', 'Bob à deux Femmes', 'Laura Nolte', 'Or', '2022-02-19'),
('Allemagne', 'Bobsleigh', 'Bob à deux Femmes', 'Mariama Jamanka', 'Argent', '2022-02-19'),
('États-Unis', 'Bobsleigh', 'Bob à deux Femmes', 'Elana Meyers Taylor', 'Bronze', '2022-02-19'),
('Allemagne', 'Bobsleigh', 'Bob à quatre Hommes', 'Francesco Friedrich', 'Or', '2022-02-20'),
('Allemagne', 'Bobsleigh', 'Bob à quatre Hommes', 'Johannes Lochner', 'Argent', '2022-02-20'),
('Canada', 'Bobsleigh', 'Bob à quatre Hommes', 'Justin Kripps', 'Bronze', '2022-02-20'),

-- SKI DE FOND
('Norvège', 'Ski de Fond', 'Skiathlon 15km+15km Hommes', 'Alexander Bolshunov (ROC)', 'Or', '2022-02-06'),
('ROC', 'Ski de Fond', 'Skiathlon 15km+15km Hommes', 'Alexander Bolshunov', 'Or', '2022-02-06'),
('ROC', 'Ski de Fond', 'Skiathlon 15km+15km Hommes', 'Denis Spitsov', 'Argent', '2022-02-06'),
('Finlande', 'Ski de Fond', 'Skiathlon 15km+15km Hommes', 'Iivo Niskanen', 'Bronze', '2022-02-06'),
('Norvège', 'Ski de Fond', 'Sprint Libre Hommes', 'Johannes Høsflot Klæbo', 'Or', '2022-02-08'),
('Italie', 'Ski de Fond', 'Sprint Libre Hommes', 'Federico Pellegrino', 'Argent', '2022-02-08'),
('ROC', 'Ski de Fond', 'Sprint Libre Hommes', 'Alexander Terentiev', 'Bronze', '2022-02-08'),
('Finlande', 'Ski de Fond', '15km Classique Hommes', 'Iivo Niskanen', 'Or', '2022-02-11'),
('ROC', 'Ski de Fond', '15km Classique Hommes', 'Alexander Bolshunov', 'Argent', '2022-02-11'),
('Norvège', 'Ski de Fond', '15km Classique Hommes', 'Johannes Høsflot Klæbo', 'Bronze', '2022-02-11'),
('ROC', 'Ski de Fond', 'Relais 4x10km Hommes', 'Équipe ROC', 'Or', '2022-02-13'),
('Norvège', 'Ski de Fond', 'Relais 4x10km Hommes', 'Équipe Norvège', 'Argent', '2022-02-13'),
('France', 'Ski de Fond', 'Relais 4x10km Hommes', 'Équipe France', 'Bronze', '2022-02-13'),
('Norvège', 'Ski de Fond', 'Sprint par Équipe Classique Hommes', 'Norvège (Valnes/Klæbo)', 'Or', '2022-02-16'),
('Finlande', 'Ski de Fond', 'Sprint par Équipe Classique Hommes', 'Finlande (Niskanen/Mäki)', 'Argent', '2022-02-16'),
('ROC', 'Ski de Fond', 'Sprint par Équipe Classique Hommes', 'ROC (Bolshunov/Terentiev)', 'Bronze', '2022-02-16'),
('ROC', 'Ski de Fond', '50km Libre Hommes', 'Alexander Bolshunov', 'Or', '2022-02-19'),
('ROC', 'Ski de Fond', '50km Libre Hommes', 'Ivan Yakimushkin', 'Argent', '2022-02-19'),
('Norvège', 'Ski de Fond', '50km Libre Hommes', 'Simen Hegstad Krüger', 'Bronze', '2022-02-19'),
('Norvège', 'Ski de Fond', 'Skiathlon 7.5km+7.5km Femmes', 'Therese Johaug', 'Or', '2022-02-05'),
('ROC', 'Ski de Fond', 'Skiathlon 7.5km+7.5km Femmes', 'Natalya Nepryayeva', 'Argent', '2022-02-05'),
('Autriche', 'Ski de Fond', 'Skiathlon 7.5km+7.5km Femmes', 'Teresa Stadlober', 'Bronze', '2022-02-05'),
('Suède', 'Ski de Fond', 'Sprint Libre Femmes', 'Jonna Sundling', 'Or', '2022-02-08'),
('Suède', 'Ski de Fond', 'Sprint Libre Femmes', 'Maja Dahlqvist', 'Argent', '2022-02-08'),
('États-Unis', 'Ski de Fond', 'Sprint Libre Femmes', 'Jessie Diggins', 'Bronze', '2022-02-08'),
('Norvège', 'Ski de Fond', '10km Classique Femmes', 'Therese Johaug', 'Or', '2022-02-10'),
('Finlande', 'Ski de Fond', '10km Classique Femmes', 'Kerttu Niskanen', 'Argent', '2022-02-10'),
('Finlande', 'Ski de Fond', '10km Classique Femmes', 'Krista Pärmäkoski', 'Bronze', '2022-02-10'),
('ROC', 'Ski de Fond', 'Relais 4x5km Femmes', 'Équipe ROC', 'Or', '2022-02-12'),
('Allemagne', 'Ski de Fond', 'Relais 4x5km Femmes', 'Équipe Allemagne', 'Argent', '2022-02-12'),
('Suède', 'Ski de Fond', 'Relais 4x5km Femmes', 'Équipe Suède', 'Bronze', '2022-02-12'),
('Allemagne', 'Ski de Fond', 'Sprint par Équipe Classique Femmes', 'Allemagne (Hennig/Carl)', 'Or', '2022-02-16'),
('Suède', 'Ski de Fond', 'Sprint par Équipe Classique Femmes', 'Suède (Dahlqvist/Sundling)', 'Argent', '2022-02-16'),
('ROC', 'Ski de Fond', 'Sprint par Équipe Classique Femmes', 'ROC (Stupak/Nepryayeva)', 'Bronze', '2022-02-16'),
('Norvège', 'Ski de Fond', '30km Libre Femmes', 'Therese Johaug', 'Or', '2022-02-20'),
('États-Unis', 'Ski de Fond', '30km Libre Femmes', 'Jessie Diggins', 'Argent', '2022-02-20'),
('Finlande', 'Ski de Fond', '30km Libre Femmes', 'Kerttu Niskanen', 'Bronze', '2022-02-20'),

-- SAUT À SKI
('Slovénie', 'Saut à Ski', 'Tremplin Normal Femmes', 'Urša Bogataj', 'Or', '2022-02-05'),
('Allemagne', 'Saut à Ski', 'Tremplin Normal Femmes', 'Katharina Althaus', 'Argent', '2022-02-05'),
('Slovénie', 'Saut à Ski', 'Tremplin Normal Femmes', 'Nika Križnar', 'Bronze', '2022-02-05'),
('Japon', 'Saut à Ski', 'Tremplin Normal Hommes', 'Ryōyū Kobayashi', 'Or', '2022-02-06'),
('Autriche', 'Saut à Ski', 'Tremplin Normal Hommes', 'Manuel Fettner', 'Argent', '2022-02-06'),
('Pologne', 'Saut à Ski', 'Tremplin Normal Hommes', 'Dawid Kubacki', 'Bronze', '2022-02-06'),
('Slovénie', 'Saut à Ski', 'Équipe Mixte', 'Équipe Slovénie', 'Or', '2022-02-07'),
('ROC', 'Saut à Ski', 'Équipe Mixte', 'Équipe ROC', 'Argent', '2022-02-07'),
('Canada', 'Saut à Ski', 'Équipe Mixte', 'Équipe Canada', 'Bronze', '2022-02-07'),
('Norvège', 'Saut à Ski', 'Grand Tremplin Hommes', 'Marius Lindvik', 'Or', '2022-02-12'),
('Japon', 'Saut à Ski', 'Grand Tremplin Hommes', 'Ryōyū Kobayashi', 'Argent', '2022-02-12'),
('Allemagne', 'Saut à Ski', 'Grand Tremplin Hommes', 'Karl Geiger', 'Bronze', '2022-02-12'),
('Autriche', 'Saut à Ski', 'Par Équipe Hommes', 'Équipe Autriche', 'Or', '2022-02-14'),
('Slovénie', 'Saut à Ski', 'Par Équipe Hommes', 'Équipe Slovénie', 'Argent', '2022-02-14'),
('Allemagne', 'Saut à Ski', 'Par Équipe Hommes', 'Équipe Allemagne', 'Bronze', '2022-02-14'),

-- COMBINÉ NORDIQUE
('Allemagne', 'Combiné Nordique', 'Tremplin Normal/10km', 'Vinzenz Geiger', 'Or', '2022-02-09'),
('Norvège', 'Combiné Nordique', 'Tremplin Normal/10km', 'Jørgen Graabak', 'Argent', '2022-02-09'),
('Autriche', 'Combiné Nordique', 'Tremplin Normal/10km', 'Lukas Greiderer', 'Bronze', '2022-02-09'),
('Norvège', 'Combiné Nordique', 'Grand Tremplin/10km', 'Jørgen Graabak', 'Or', '2022-02-15'),
('Norvège', 'Combiné Nordique', 'Grand Tremplin/10km', 'Jens Lurås Oftebro', 'Argent', '2022-02-15'),
('Japon', 'Combiné Nordique', 'Grand Tremplin/10km', 'Akito Watabe', 'Bronze', '2022-02-15'),
('Norvège', 'Combiné Nordique', 'Par Équipe', 'Équipe Norvège', 'Or', '2022-02-17'),
('Allemagne', 'Combiné Nordique', 'Par Équipe', 'Équipe Allemagne', 'Argent', '2022-02-17'),
('Japon', 'Combiné Nordique', 'Par Équipe', 'Équipe Japon', 'Bronze', '2022-02-17'),

-- PATINAGE DE VITESSE
('Pays-Bas', 'Patinage de Vitesse', '3000m Femmes', 'Irene Schouten', 'Or', '2022-02-05'),
('Italie', 'Patinage de Vitesse', '3000m Femmes', 'Francesca Lollobrigida', 'Argent', '2022-02-05'),
('Canada', 'Patinage de Vitesse', '3000m Femmes', 'Isabelle Weidemann', 'Bronze', '2022-02-05'),
('Suède', 'Patinage de Vitesse', '5000m Hommes', 'Nils van der Poel', 'Or', '2022-02-06'),
('Pays-Bas', 'Patinage de Vitesse', '5000m Hommes', 'Patrick Roest', 'Argent', '2022-02-06'),
('Norvège', 'Patinage de Vitesse', '5000m Hommes', 'Hallgeir Engebråten', 'Bronze', '2022-02-06'),
('Pays-Bas', 'Patinage de Vitesse', '1500m Femmes', 'Ireen Wüst', 'Or', '2022-02-07'),
('Japon', 'Patinage de Vitesse', '1500m Femmes', 'Miho Takagi', 'Argent', '2022-02-07'),
('Pays-Bas', 'Patinage de Vitesse', '1500m Femmes', 'Antoinette de Jong', 'Bronze', '2022-02-07'),
('Pays-Bas', 'Patinage de Vitesse', '1500m Hommes', 'Kjeld Nuis', 'Or', '2022-02-08'),
('Pays-Bas', 'Patinage de Vitesse', '1500m Hommes', 'Thomas Krol', 'Argent', '2022-02-08'),
('Corée du Sud', 'Patinage de Vitesse', '1500m Hommes', 'Kim Min-seok', 'Bronze', '2022-02-08'),
('Pays-Bas', 'Patinage de Vitesse', '5000m Femmes', 'Irene Schouten', 'Or', '2022-02-10'),
('Canada', 'Patinage de Vitesse', '5000m Femmes', 'Isabelle Weidemann', 'Argent', '2022-02-10'),
('République Tchèque', 'Patinage de Vitesse', '5000m Femmes', 'Martina Sáblíková', 'Bronze', '2022-02-10'),
('Suède', 'Patinage de Vitesse', '10000m Hommes', 'Nils van der Poel', 'Or', '2022-02-11'),
('Pays-Bas', 'Patinage de Vitesse', '10000m Hommes', 'Patrick Roest', 'Argent', '2022-02-11'),
('Italie', 'Patinage de Vitesse', '10000m Hommes', 'Davide Ghiotto', 'Bronze', '2022-02-11'),
('Chine', 'Patinage de Vitesse', '500m Hommes', 'Gao Tingyu', 'Or', '2022-02-12'),
('Corée du Sud', 'Patinage de Vitesse', '500m Hommes', 'Cha Min-kyu', 'Argent', '2022-02-12'),
('Japon', 'Patinage de Vitesse', '500m Hommes', 'Wataru Morishige', 'Bronze', '2022-02-12'),
('États-Unis', 'Patinage de Vitesse', '500m Femmes', 'Erin Jackson', 'Or', '2022-02-13'),
('Japon', 'Patinage de Vitesse', '500m Femmes', 'Miho Takagi', 'Argent', '2022-02-13'),
('ROC', 'Patinage de Vitesse', '500m Femmes', 'Angelina Golikova', 'Bronze', '2022-02-13'),
('Canada', 'Patinage de Vitesse', 'Poursuite par Équipe Femmes', 'Équipe Canada', 'Or', '2022-02-15'),
('Japon', 'Patinage de Vitesse', 'Poursuite par Équipe Femmes', 'Équipe Japon', 'Argent', '2022-02-15'),
('Pays-Bas', 'Patinage de Vitesse', 'Poursuite par Équipe Femmes', 'Équipe Pays-Bas', 'Bronze', '2022-02-15'),
('Norvège', 'Patinage de Vitesse', 'Poursuite par Équipe Hommes', 'Équipe Norvège', 'Or', '2022-02-15'),
('ROC', 'Patinage de Vitesse', 'Poursuite par Équipe Hommes', 'Équipe ROC', 'Argent', '2022-02-15'),
('États-Unis', 'Patinage de Vitesse', 'Poursuite par Équipe Hommes', 'Équipe USA', 'Bronze', '2022-02-15'),
('Japon', 'Patinage de Vitesse', '1000m Femmes', 'Miho Takagi', 'Or', '2022-02-17'),
('Pays-Bas', 'Patinage de Vitesse', '1000m Femmes', 'Jutta Leerdam', 'Argent', '2022-02-17'),
('États-Unis', 'Patinage de Vitesse', '1000m Femmes', 'Brittany Bowe', 'Bronze', '2022-02-17'),
('Pays-Bas', 'Patinage de Vitesse', '1000m Hommes', 'Thomas Krol', 'Or', '2022-02-18'),
('Canada', 'Patinage de Vitesse', '1000m Hommes', 'Laurent Dubreuil', 'Argent', '2022-02-18'),
('Norvège', 'Patinage de Vitesse', '1000m Hommes', 'Håvard Holmefjord Lorentzen', 'Bronze', '2022-02-18'),
('Belgique', 'Patinage de Vitesse', 'Mass Start Hommes', 'Bart Swings', 'Or', '2022-02-19'),
('Corée du Sud', 'Patinage de Vitesse', 'Mass Start Hommes', 'Chung Jae-won', 'Argent', '2022-02-19'),
('Corée du Sud', 'Patinage de Vitesse', 'Mass Start Hommes', 'Lee Seung-hoon', 'Bronze', '2022-02-19'),
('Pays-Bas', 'Patinage de Vitesse', 'Mass Start Femmes', 'Irene Schouten', 'Or', '2022-02-19'),
('Canada', 'Patinage de Vitesse', 'Mass Start Femmes', 'Ivanie Blondin', 'Argent', '2022-02-19'),
('Italie', 'Patinage de Vitesse', 'Mass Start Femmes', 'Francesca Lollobrigida', 'Bronze', '2022-02-19'),

-- PATINAGE DE VITESSE SUR PISTE COURTE
('Chine', 'Short Track', 'Relais Mixte 2000m', 'Équipe Chine', 'Or', '2022-02-05'),
('Italie', 'Short Track', 'Relais Mixte 2000m', 'Équipe Italie', 'Argent', '2022-02-05'),
('Hongrie', 'Short Track', 'Relais Mixte 2000m', 'Équipe Hongrie', 'Bronze', '2022-02-05'),
('Chine', 'Short Track', '1000m Hommes', 'Ren Ziwei', 'Or', '2022-02-07'),
('Chine', 'Short Track', '1000m Hommes', 'Li Wenlong', 'Argent', '2022-02-07'),
('Hongrie', 'Short Track', '1000m Hommes', 'Liu Shaoang', 'Bronze', '2022-02-07'),
('Italie', 'Short Track', '500m Femmes', 'Arianna Fontana', 'Or', '2022-02-07'),
('Pays-Bas', 'Short Track', '500m Femmes', 'Suzanne Schulting', 'Argent', '2022-02-07'),
('Canada', 'Short Track', '500m Femmes', 'Kim Boutin', 'Bronze', '2022-02-07'),
('Corée du Sud', 'Short Track', '1500m Hommes', 'Hwang Dae-heon', 'Or', '2022-02-09'),
('Canada', 'Short Track', '1500m Hommes', 'Steven Dubois', 'Argent', '2022-02-09'),
('ROC', 'Short Track', '1500m Hommes', 'Semion Elistratov', 'Bronze', '2022-02-09'),
('Pays-Bas', 'Short Track', '1000m Femmes', 'Suzanne Schulting', 'Or', '2022-02-11'),
('Corée du Sud', 'Short Track', '1000m Femmes', 'Choi Min-jeong', 'Argent', '2022-02-11'),
('Belgique', 'Short Track', '1000m Femmes', 'Hanne Desmet', 'Bronze', '2022-02-11'),
('Pays-Bas', 'Short Track', 'Relais 3000m Femmes', 'Équipe Pays-Bas', 'Or', '2022-02-13'),
('Corée du Sud', 'Short Track', 'Relais 3000m Femmes', 'Équipe Corée du Sud', 'Argent', '2022-02-13'),
('Chine', 'Short Track', 'Relais 3000m Femmes', 'Équipe Chine', 'Bronze', '2022-02-13'),
('Hongrie', 'Short Track', '500m Hommes', 'Liu Shaoang', 'Or', '2022-02-13'),
('ROC', 'Short Track', '500m Hommes', 'Konstantin Ivliev', 'Argent', '2022-02-13'),
('Canada', 'Short Track', '500m Hommes', 'Steven Dubois', 'Bronze', '2022-02-13'),
('Canada', 'Short Track', 'Relais 5000m Hommes', 'Équipe Canada', 'Or', '2022-02-16'),
('Corée du Sud', 'Short Track', 'Relais 5000m Hommes', 'Équipe Corée du Sud', 'Argent', '2022-02-16'),
('Italie', 'Short Track', 'Relais 5000m Hommes', 'Équipe Italie', 'Bronze', '2022-02-16'),
('Corée du Sud', 'Short Track', '1500m Femmes', 'Choi Min-jeong', 'Or', '2022-02-16'),
('Italie', 'Short Track', '1500m Femmes', 'Arianna Fontana', 'Argent', '2022-02-16'),
('Pays-Bas', 'Short Track', '1500m Femmes', 'Suzanne Schulting', 'Bronze', '2022-02-16');